### ISSUE TITLE
Brak atrybucji

### ISSUE THREAD

**Issue by enedil** [OpenUSOS/OpenUSOS-server#1]
Jeden z plików tego repozytorium został zapożyczony z 
https://github.com/MUCI/usosapi-python/blob/master/usosapi.py
i brakuje atrybucji.

**Comment by oskarkulinski** [comment]
Attribution added, we wanted to wait for the developers to add MIT license to their repository, but they never did, despite their promise. Looks like they will never do it. Thanks for pointing it out.
